export type RootStackParamList = {
  Main: undefined;
  Profile: undefined;
  Login: undefined;
  Logout: undefined;
  CmdK: undefined;
  FeedBuilder: undefined;
  Post: { reply?: string; quote?: string } | undefined;
  Receive: undefined;
  Minting: undefined;
  Send: undefined;
  SendEcash: { pubkey: string; noteId?: string };
  Scan: { mode?: 'share' | 'scan' } | undefined;
  Tapcash: undefined;
  Lightning: { invoice?: string } | undefined;
  ProfileStub: { path: 'relays' | 'wallet' | 'theme' | 'nprofile' };
  RelayInfos: { subId?: string; relays: string[]; statuses?: Record<string, string> };
  PublicProfile: { pubkey: string };
  Kind1Thread: { nevent: string };
  Kind30023Thread: { naddr: string };
  Kind1111Comments: { nevent: string };
  Tags: { tags: string[] };
  ChatThread: { peerPubkey: string };
  Notifications: undefined;
};
