export type RootStackParamList = {
  Main: undefined;
  Profile: undefined;
  Login: undefined;
  Logout: undefined;
  CmdK: undefined;
  FeedBuilder: undefined;
  Post: { reply?: string; quote?: string } | undefined;
  Receive: undefined;
  Minting: undefined;
  Send: undefined;
  NewChat: undefined;
  SendEcash: { pubkey: string; noteId?: string };
  Share: { nevent: string; naddr?: string };
  Scan: { mode?: 'share' | 'scan' } | undefined;
  Tapcash: undefined;
  Lightning: { invoice?: string } | undefined;
  Theme: undefined;
  Keys: undefined;
  Mints: undefined;
  RelayPreferences: undefined;
  Wallet: undefined;
  ProfileStub: { path: 'relays' | 'wallet' | 'nprofile' };
  RelayInfos: {
    subId?: string;
    relays: string[];
    statuses?: Record<string, string>;
    mode?: 'relays' | 'communities';
  };
  Community: {
    description?: string;
    icon?: string;
    name?: string;
    relationship?: 'follow' | 'belong';
    relay: string;
  };
  PublicProfile: { pubkey: string };
  Kind1Thread: { nevent: string };
  Kind30023Thread: { naddr: string };
  LiveStream: { nevent: string };
  Kind1111Comments: { nevent: string };
  Tags: { tags: string[] };
  ChatThread: { peerPubkey: string };
  Notifications: undefined;
};
